
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action Action1;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action EditAction1;
	private global::Gtk.Action HelpAction1;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Table table1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Label label11;
	private global::Gtk.Button btnCompile;
	private global::Gtk.Entry txtProgram;
	private global::Gtk.FileChooserButton filechooserbutton1;
	private global::Gtk.MenuBar menubar3;
	private global::Gtk.Notebook nbOutput;
	private global::Gtk.ScrolledWindow scrolledwindow3;
	private global::Gtk.TextView txtOutput;
	private global::Gtk.Label tabOutput;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtCfile;
	private global::Gtk.Label tabCFile;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView txtCLfile;
	private global::Gtk.Label tabCHFile;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView txtCLHfile;
	private global::Gtk.Label tabCLHfile;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Table table2;
	private global::Gtk.RadioButton chkBS2000;
	private global::Gtk.RadioButton chkCobol2k2;
	private global::Gtk.RadioButton chkCobol85;
	private global::Gtk.CheckButton chkDebug;
	private global::Gtk.RadioButton chkDefault;
	private global::Gtk.CheckButton chkDll;
	private global::Gtk.CheckButton chkExecute;
	private global::Gtk.RadioButton chkIBM;
	private global::Gtk.RadioButton chkMicroFocus;
	private global::Gtk.RadioButton chkMVS;
	private global::Gtk.CheckButton chkNoTrunc;
	private global::Gtk.CheckButton chkSubRoutine;
	private global::Gtk.CheckButton chkTraceAll;
	private global::Gtk.CheckButton chkTraceYN;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label10;
	private global::Gtk.Entry txtCopyInc;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label7;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.Label lblOS;
	private global::Gtk.Entry txtAddSwitch;
	private global::Gtk.Entry txtLibrary;
	private global::Gtk.Entry txtPgmParams;
	private global::Gtk.Label label3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.Action1 = new global::Gtk.Action ("Action1", null, null, null);
		this.Action1.ShortLabel = "";
		w1.Add (this.Action1, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.EditAction1 = new global::Gtk.Action ("EditAction1", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction1, null);
		this.HelpAction1 = new global::Gtk.Action ("HelpAction1", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction1, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1024;
		this.HeightRequest = 768;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("OpenCOBOL Interactive Compiler v1.0 rc .001");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, ".\\oc-icon.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(1)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.HeightRequest = 0;
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.WidthRequest = 600;
		this.fixed2.HeightRequest = 0;
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Program</b>");
		this.label11.UseMarkup = true;
		this.fixed2.Add (this.label11);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label11]));
		w2.X = 13;
		w2.Y = 7;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnCompile = new global::Gtk.Button ();
		this.btnCompile.CanFocus = true;
		this.btnCompile.Name = "btnCompile";
		this.btnCompile.UseUnderline = true;
		this.btnCompile.Label = global::Mono.Unix.Catalog.GetString ("Compile");
		this.fixed2.Add (this.btnCompile);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnCompile]));
		w3.X = 912;
		w3.Y = 2;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtProgram = new global::Gtk.Entry ();
		this.txtProgram.CanFocus = true;
		this.txtProgram.Name = "txtProgram";
		this.txtProgram.IsEditable = true;
		this.txtProgram.WidthChars = 120;
		this.txtProgram.InvisibleChar = '●';
		this.fixed2.Add (this.txtProgram);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtProgram]));
		w4.X = 71;
		w4.Y = 4;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton1.Name = "filechooserbutton1";
		this.fixed2.Add (this.filechooserbutton1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.filechooserbutton1]));
		w5.X = 804;
		w5.Y = 4;
		this.hbox3.Add (this.fixed2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed2]));
		w6.Position = 0;
		this.table1.Add (this.hbox3);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox3]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar3\'><menu name=\'FileAction\' action=\'FileAction\'/><menu n" +
			"ame=\'EditAction1\' action=\'EditAction1\'/><menu name=\'HelpAction1\' action=\'HelpAct" +
			"ion1\'><menuitem name=\'AboutAction\' action=\'AboutAction\'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.table1.Add (this.menubar3);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.menubar3]));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.nbOutput = new global::Gtk.Notebook ();
		this.nbOutput.CanFocus = true;
		this.nbOutput.Name = "nbOutput";
		this.nbOutput.CurrentPage = 0;
		// Container child nbOutput.Gtk.Notebook+NotebookChild
		this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow3.CanFocus = true;
		this.scrolledwindow3.Name = "scrolledwindow3";
		this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow3.Gtk.Container+ContainerChild
		this.txtOutput = new global::Gtk.TextView ();
		this.txtOutput.CanFocus = true;
		this.txtOutput.Name = "txtOutput";
		this.scrolledwindow3.Add (this.txtOutput);
		this.nbOutput.Add (this.scrolledwindow3);
		// Notebook tab
		this.tabOutput = new global::Gtk.Label ();
		this.tabOutput.Name = "tabOutput";
		this.tabOutput.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Output</b>");
		this.tabOutput.UseMarkup = true;
		this.nbOutput.SetTabLabel (this.scrolledwindow3, this.tabOutput);
		this.tabOutput.ShowAll ();
		// Container child nbOutput.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtCfile = new global::Gtk.TextView ();
		this.txtCfile.CanFocus = true;
		this.txtCfile.Name = "txtCfile";
		this.GtkScrolledWindow.Add (this.txtCfile);
		this.nbOutput.Add (this.GtkScrolledWindow);
		global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.nbOutput [this.GtkScrolledWindow]));
		w12.Position = 1;
		// Notebook tab
		this.tabCFile = new global::Gtk.Label ();
		this.tabCFile.Name = "tabCFile";
		this.tabCFile.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>.c File </b>");
		this.tabCFile.UseMarkup = true;
		this.nbOutput.SetTabLabel (this.GtkScrolledWindow, this.tabCFile);
		this.tabCFile.ShowAll ();
		// Container child nbOutput.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtCLfile = new global::Gtk.TextView ();
		this.txtCLfile.CanFocus = true;
		this.txtCLfile.Name = "txtCLfile";
		this.GtkScrolledWindow1.Add (this.txtCLfile);
		this.nbOutput.Add (this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.nbOutput [this.GtkScrolledWindow1]));
		w14.Position = 2;
		// Notebook tab
		this.tabCHFile = new global::Gtk.Label ();
		this.tabCHFile.Name = "tabCHFile";
		this.tabCHFile.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>.c.h File </b>");
		this.tabCHFile.UseMarkup = true;
		this.nbOutput.SetTabLabel (this.GtkScrolledWindow1, this.tabCHFile);
		this.tabCHFile.ShowAll ();
		// Container child nbOutput.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.txtCLHfile = new global::Gtk.TextView ();
		this.txtCLHfile.CanFocus = true;
		this.txtCLHfile.Name = "txtCLHfile";
		this.GtkScrolledWindow2.Add (this.txtCLHfile);
		this.nbOutput.Add (this.GtkScrolledWindow2);
		global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.nbOutput [this.GtkScrolledWindow2]));
		w16.Position = 3;
		// Notebook tab
		this.tabCLHfile = new global::Gtk.Label ();
		this.tabCLHfile.Name = "tabCLHfile";
		this.tabCLHfile.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>.c.l.h File </b>");
		this.tabCLHfile.UseMarkup = true;
		this.tabCLHfile.Justify = ((global::Gtk.Justification)(2));
		this.nbOutput.SetTabLabel (this.GtkScrolledWindow2, this.tabCLHfile);
		this.tabCLHfile.ShowAll ();
		this.table1.Add (this.nbOutput);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.nbOutput]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(8)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		this.table2.BorderWidth = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.chkBS2000 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("BS2000"));
		this.chkBS2000.CanFocus = true;
		this.chkBS2000.Name = "chkBS2000";
		this.chkBS2000.DrawIndicator = true;
		this.chkBS2000.UseUnderline = true;
		this.chkBS2000.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.table2.Add (this.chkBS2000);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkBS2000]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XPadding = ((uint)(31));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkCobol2k2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("COBOL 2002"));
		this.chkCobol2k2.CanFocus = true;
		this.chkCobol2k2.Name = "chkCobol2k2";
		this.chkCobol2k2.DrawIndicator = true;
		this.chkCobol2k2.UseUnderline = true;
		this.chkCobol2k2.Group = this.chkBS2000.Group;
		this.table2.Add (this.chkCobol2k2);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkCobol2k2]));
		w19.TopAttach = ((uint)(3));
		w19.BottomAttach = ((uint)(4));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XPadding = ((uint)(31));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkCobol85 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("COBOL 85"));
		this.chkCobol85.CanFocus = true;
		this.chkCobol85.Name = "chkCobol85";
		this.chkCobol85.DrawIndicator = true;
		this.chkCobol85.UseUnderline = true;
		this.chkCobol85.Group = this.chkBS2000.Group;
		this.table2.Add (this.chkCobol85);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkCobol85]));
		w20.TopAttach = ((uint)(2));
		w20.BottomAttach = ((uint)(3));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XPadding = ((uint)(31));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkDebug = new global::Gtk.CheckButton ();
		this.chkDebug.CanFocus = true;
		this.chkDebug.Name = "chkDebug";
		this.chkDebug.Label = global::Mono.Unix.Catalog.GetString ("Compile Debug Lines");
		this.chkDebug.DrawIndicator = true;
		this.chkDebug.UseUnderline = true;
		this.table2.Add (this.chkDebug);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkDebug]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkDefault = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("DEFAULT"));
		this.chkDefault.CanFocus = true;
		this.chkDefault.Name = "chkDefault";
		this.chkDefault.DrawIndicator = true;
		this.chkDefault.UseUnderline = true;
		this.chkDefault.Group = this.chkBS2000.Group;
		this.table2.Add (this.chkDefault);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkDefault]));
		w22.TopAttach = ((uint)(4));
		w22.BottomAttach = ((uint)(5));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.XPadding = ((uint)(31));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkDll = new global::Gtk.CheckButton ();
		this.chkDll.CanFocus = true;
		this.chkDll.Name = "chkDll";
		this.chkDll.Label = global::Mono.Unix.Catalog.GetString ("Generate MAIN PROGRAMS as DLLs");
		this.chkDll.DrawIndicator = true;
		this.chkDll.UseUnderline = true;
		this.table2.Add (this.chkDll);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkDll]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkExecute = new global::Gtk.CheckButton ();
		this.chkExecute.CanFocus = true;
		this.chkExecute.Name = "chkExecute";
		this.chkExecute.Label = global::Mono.Unix.Catalog.GetString ("Execute upon successful completion");
		this.chkExecute.DrawIndicator = true;
		this.chkExecute.UseUnderline = true;
		this.table2.Add (this.chkExecute);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkExecute]));
		w24.TopAttach = ((uint)(4));
		w24.BottomAttach = ((uint)(5));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkIBM = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("IBM"));
		this.chkIBM.CanFocus = true;
		this.chkIBM.Name = "chkIBM";
		this.chkIBM.DrawIndicator = true;
		this.chkIBM.UseUnderline = true;
		this.chkIBM.Group = this.chkBS2000.Group;
		this.table2.Add (this.chkIBM);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkIBM]));
		w25.TopAttach = ((uint)(5));
		w25.BottomAttach = ((uint)(6));
		w25.LeftAttach = ((uint)(1));
		w25.RightAttach = ((uint)(2));
		w25.XPadding = ((uint)(31));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkMicroFocus = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("MicroFocus"));
		this.chkMicroFocus.CanFocus = true;
		this.chkMicroFocus.Name = "chkMicroFocus";
		this.chkMicroFocus.DrawIndicator = true;
		this.chkMicroFocus.UseUnderline = true;
		this.chkMicroFocus.Group = this.chkBS2000.Group;
		this.table2.Add (this.chkMicroFocus);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkMicroFocus]));
		w26.TopAttach = ((uint)(6));
		w26.BottomAttach = ((uint)(7));
		w26.LeftAttach = ((uint)(1));
		w26.RightAttach = ((uint)(2));
		w26.XPadding = ((uint)(31));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkMVS = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("mvs"));
		this.chkMVS.CanFocus = true;
		this.chkMVS.Name = "chkMVS";
		this.chkMVS.DrawIndicator = true;
		this.chkMVS.UseUnderline = true;
		this.chkMVS.Group = this.chkBS2000.Group;
		this.table2.Add (this.chkMVS);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkMVS]));
		w27.TopAttach = ((uint)(7));
		w27.BottomAttach = ((uint)(8));
		w27.LeftAttach = ((uint)(1));
		w27.RightAttach = ((uint)(2));
		w27.XPadding = ((uint)(31));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkNoTrunc = new global::Gtk.CheckButton ();
		this.chkNoTrunc.CanFocus = true;
		this.chkNoTrunc.Name = "chkNoTrunc";
		this.chkNoTrunc.Label = global::Mono.Unix.Catalog.GetString ("Do not truncate COMP/BINARY values");
		this.chkNoTrunc.DrawIndicator = true;
		this.chkNoTrunc.UseUnderline = true;
		this.table2.Add (this.chkNoTrunc);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkNoTrunc]));
		w28.TopAttach = ((uint)(5));
		w28.BottomAttach = ((uint)(6));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkSubRoutine = new global::Gtk.CheckButton ();
		this.chkSubRoutine.CanFocus = true;
		this.chkSubRoutine.Name = "chkSubRoutine";
		this.chkSubRoutine.Label = global::Mono.Unix.Catalog.GetString ("This program is a SUBROUTINE");
		this.chkSubRoutine.DrawIndicator = true;
		this.chkSubRoutine.UseUnderline = true;
		this.table2.Add (this.chkSubRoutine);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkSubRoutine]));
		w29.TopAttach = ((uint)(3));
		w29.BottomAttach = ((uint)(4));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkTraceAll = new global::Gtk.CheckButton ();
		this.chkTraceAll.CanFocus = true;
		this.chkTraceAll.Name = "chkTraceAll";
		this.chkTraceAll.Label = global::Mono.Unix.Catalog.GetString ("Trace procedures + statements");
		this.chkTraceAll.DrawIndicator = true;
		this.chkTraceAll.UseUnderline = true;
		this.table2.Add (this.chkTraceAll);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkTraceAll]));
		w30.TopAttach = ((uint)(7));
		w30.BottomAttach = ((uint)(8));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.chkTraceYN = new global::Gtk.CheckButton ();
		this.chkTraceYN.CanFocus = true;
		this.chkTraceYN.Name = "chkTraceYN";
		this.chkTraceYN.Label = global::Mono.Unix.Catalog.GetString ("Trace procedures");
		this.chkTraceYN.DrawIndicator = true;
		this.chkTraceYN.UseUnderline = true;
		this.table2.Add (this.chkTraceYN);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkTraceYN]));
		w31.TopAttach = ((uint)(6));
		w31.BottomAttach = ((uint)(7));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.Xalign = 0F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Add  \"directory\" to copy/include search path</b>");
		this.label10.UseMarkup = true;
		this.fixed1.Add (this.label10);
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtCopyInc = new global::Gtk.Entry ();
		this.txtCopyInc.CanFocus = true;
		this.txtCopyInc.Name = "txtCopyInc";
		this.txtCopyInc.IsEditable = true;
		this.txtCopyInc.WidthChars = 95;
		this.txtCopyInc.MaxLength = 135;
		this.txtCopyInc.InvisibleChar = '●';
		this.fixed1.Add (this.txtCopyInc);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtCopyInc]));
		w33.Y = 28;
		this.table2.Add (this.fixed1);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed1]));
		w34.TopAttach = ((uint)(5));
		w34.BottomAttach = ((uint)(6));
		w34.LeftAttach = ((uint)(2));
		w34.RightAttach = ((uint)(3));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Switches</b>");
		this.label1.UseMarkup = true;
		this.table2.Add (this.label1);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Configuration</b>");
		this.label2.UseMarkup = true;
		this.table2.Add (this.label2);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Program parameters (if any)</b>");
		this.label7.UseMarkup = true;
		this.table2.Add (this.label7);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
		w37.TopAttach = ((uint)(3));
		w37.BottomAttach = ((uint)(4));
		w37.LeftAttach = ((uint)(2));
		w37.RightAttach = ((uint)(3));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Additional Compiler Switches</b>");
		this.label8.UseMarkup = true;
		this.table2.Add (this.label8);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
		w38.TopAttach = ((uint)(1));
		w38.BottomAttach = ((uint)(2));
		w38.LeftAttach = ((uint)(2));
		w38.RightAttach = ((uint)(3));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.Xalign = 0F;
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Add \"directory\" to library search path </b>");
		this.label9.UseMarkup = true;
		this.table2.Add (this.label9);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
		w39.TopAttach = ((uint)(6));
		w39.BottomAttach = ((uint)(7));
		w39.LeftAttach = ((uint)(2));
		w39.RightAttach = ((uint)(3));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.lblOS = new global::Gtk.Label ();
		this.lblOS.Name = "lblOS";
		this.lblOS.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.lblOS.UseMarkup = true;
		this.table2.Add (this.lblOS);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblOS]));
		w40.LeftAttach = ((uint)(2));
		w40.RightAttach = ((uint)(3));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtAddSwitch = new global::Gtk.Entry ();
		this.txtAddSwitch.CanFocus = true;
		this.txtAddSwitch.Name = "txtAddSwitch";
		this.txtAddSwitch.IsEditable = true;
		this.txtAddSwitch.WidthChars = 95;
		this.txtAddSwitch.MaxLength = 135;
		this.txtAddSwitch.InvisibleChar = '●';
		this.table2.Add (this.txtAddSwitch);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtAddSwitch]));
		w41.TopAttach = ((uint)(2));
		w41.BottomAttach = ((uint)(3));
		w41.LeftAttach = ((uint)(2));
		w41.RightAttach = ((uint)(3));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtLibrary = new global::Gtk.Entry ();
		this.txtLibrary.CanFocus = true;
		this.txtLibrary.Name = "txtLibrary";
		this.txtLibrary.IsEditable = true;
		this.txtLibrary.WidthChars = 89;
		this.txtLibrary.MaxLength = 135;
		this.txtLibrary.InvisibleChar = '●';
		this.table2.Add (this.txtLibrary);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtLibrary]));
		w42.TopAttach = ((uint)(7));
		w42.BottomAttach = ((uint)(8));
		w42.LeftAttach = ((uint)(2));
		w42.RightAttach = ((uint)(3));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtPgmParams = new global::Gtk.Entry ();
		this.txtPgmParams.CanFocus = true;
		this.txtPgmParams.Name = "txtPgmParams";
		this.txtPgmParams.IsEditable = true;
		this.txtPgmParams.WidthChars = 95;
		this.txtPgmParams.MaxLength = 135;
		this.txtPgmParams.InvisibleChar = '●';
		this.table2.Add (this.txtPgmParams);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtPgmParams]));
		w43.TopAttach = ((uint)(4));
		w43.BottomAttach = ((uint)(5));
		w43.LeftAttach = ((uint)(2));
		w43.RightAttach = ((uint)(3));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox4.Add (this.table2);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.table2]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		this.notebook1.Add (this.hbox4);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Common Settings</b>");
		this.label3.UseMarkup = true;
		this.notebook1.SetTabLabel (this.hbox4, this.label3);
		this.label3.ShowAll ();
		this.table1.Add (this.notebook1);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1 [this.notebook1]));
		w46.TopAttach = ((uint)(2));
		w46.BottomAttach = ((uint)(3));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1024;
		this.DefaultHeight = 768;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.HelpAction1.Activated += new global::System.EventHandler (this.OnHelpAction1Activated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.btnCompile.Clicked += new global::System.EventHandler (this.OnBtnCompileClicked);
		this.filechooserbutton1.SelectionChanged += new global::System.EventHandler (this.OnFilechooserbutton1SelectionChanged);
	}
}
